info:
  app:
    name: NetCheck API
    description: Website performance and availability monitoring app
  java:
    vendor: ${java.specification.vendor}
    version: ${java.version}
    vm-name: ${java.vm.name}
    vm-version: ${java.vm.version}
    version-date: ${java.version.date}
  os:
    name: ${os.name}
spring:
  jmx:
    enabled: false
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 20
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.db}
    username: ${postgres.user}
    password: ${postgres.password}
  batch:
    initialize-schema: never
    job:
      enabled: false
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
settings:
  cors:
    origin: "*"
  schedulers:
    cleanup:
      enabled: false
      deleteOlderThan: 3
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: ${settings.cors.origin}
        allowed-methods: "GET"
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always
      show-components: always
