spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.db}
    username: ${postgres.user}
    password: ${postgres.password}
  batch:
    initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
settings:
  cors:
    origin: "*"
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: ${settings.cors.origin}
        allowed-methods: "GET,POST"
  endpoint:
    health:
      show-details: always
      show-components: always