name: Run Unit Tests

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: maven:3.6-adoptopenjdk-11-openj9

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgresql
          POSTGRES_PASSWORD: letmein
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies and run tests
        run: mvn clean install
