name: Run Unit Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: maven:3.6-adoptopenjdk-11-openj9

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgresql
          POSTGRES_PASSWORD: letmein
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies and run tests
        run: mvn clean install
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgresql
          POSTGRES_PASSWORD: letmein
          POSTGRES_DB: test_db
      - name: Upload jar file
        uses: actions/upload-artifact@v1
        with:
          name: jar
          path: target/netcheck.jar

  release:
    name: Create Github Release
    runs-on: ubuntu-latest
    container: golang
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download jar file
        uses: actions/download-artifact@v1
        with:
          name: jar
      - name: Extract repo name
        run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
      - name: Publish Release on GitHub
        run: |
          go get github.com/tcnksm/ghr
          VERSION=`cat ./version.txt`
          shell: bash
          ghr -t ${{ secrets.GITHUB_TOKEN }} -u ${GITHUB_ACTOR} -r ${REPOSITORY_NAME} -c ${GITHUB_SHA} -delete ${VERSION} ./jar/
